services:
  mysql:
    image: mysql:8.0
    container_name: crawler_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crawler_db
      MYSQL_USER: crawler_user
      MYSQL_PASSWORD: crawler_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crawler_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: crawler_backend
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=crawler_user
      - DB_PASSWORD=crawler_password
      - DB_NAME=crawler_db
      - PORT=8080
      - GIN_MODE=release
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - crawler_network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: crawler_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - crawler_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  crawler_network:
    driver: bridge