version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: webcrawler_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webcrawler
      MYSQL_USER: webcrawler_user
      MYSQL_PASSWORD: webcrawler_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: webcrawler_backend
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: webcrawler
      DB_USER: webcrawler_user
      DB_PASSWORD: webcrawler_pass
      JWT_SECRET: your-jwt-secret-key-here
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: go run main.go

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: webcrawler_frontend
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:8080
      REACT_APP_WS_URL: ws://localhost:8080
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

volumes:
  mysql_data: